name: Maven Test

on:
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean test

    - name: Publish Test Report
      if: success() || failure()
      uses: scacap/action-surefire-report@v1
